#include "rbt.tpp"
#include "visual.hpp"
#include <cassert>
#include <cmath>
#include <iostream>
#include <string>
#include <vector>

// Generated by Gemini

// ---------------------------------------------------------------------
// Invariant & Property Check Helpers
// ---------------------------------------------------------------------

template <typename T>
int checkRBInvariant(const Node<T>* node, const Node<T>* sentinel, bool& ok) {
    if (node == sentinel) {
        return 1; // Sentinel NIL nodes are BLACK with black-height 1
    }

    // Property 1: No consecutive RED nodes
    if (node->color == Color::RED) {
        if (node->left->color == Color::RED || node->right->color == Color::RED) {
            std::cerr << "  [FAIL] Red node has red child at val=" << node->val << "\n";
            ok = false;
        }
    }

    // Property 2: Valid Parent Pointers
    if (node->left != sentinel && node->left->parent != node) {
        std::cerr << "  [FAIL] Parent pointer corrupt at left child of val=" << node->val << "\n";
        ok = false;
    }
    if (node->right != sentinel && node->right->parent != node) {
        std::cerr << "  [FAIL] Parent pointer corrupt at right child of val=" << node->val << "\n";
        ok = false;
    }

    int leftBlackHeight = checkRBInvariant(node->left, sentinel, ok);
    int rightBlackHeight = checkRBInvariant(node->right, sentinel, ok);

    // Property 3: Equal Black-Height on all paths
    if (leftBlackHeight != rightBlackHeight) {
        std::cerr << "  [FAIL] Black-height mismatch at node val=" << node->val
                  << " (lh=" << leftBlackHeight << ", rh=" << rightBlackHeight << ")\n";
        ok = false;
    }

    return leftBlackHeight + (node->color == Color::BLACK ? 1 : 0);
}

template <typename T>
bool checkBSTOrder(const Node<T>* node, const Node<T>* sentinel, const T* lowExclusive, const T* highExclusive) {
    if (node == sentinel) return true;

    if (lowExclusive && !(*lowExclusive < node->val)) return false;
    if (highExclusive && !(node->val < *highExclusive)) return false;

    return checkBSTOrder(node->left, sentinel, lowExclusive, &node->val) &&
           checkBSTOrder(node->right, sentinel, &node->val, highExclusive);
}

template <typename T>
bool isValidRBTree(const RBTree<T>& tree) {
    bool ok = true;
    Node<T>* root = tree.getRoot();
    Node<T>* sentinel = tree.getNIL();

    if (root == sentinel) return true;

    if (root->color != Color::BLACK) {
        std::cerr << "  [FAIL] Root is RED!\n";
        ok = false;
    }

    checkRBInvariant(root, sentinel, ok);
    ok = ok && checkBSTOrder<T>(root, sentinel, nullptr, nullptr);
    return ok;
}

template <typename T>
void collectInorder(const Node<T>* node, const Node<T>* sentinel, std::vector<T>& out) {
    if (node == sentinel) return;
    collectInorder(node->left, sentinel, out);
    out.push_back(node->val);
    collectInorder(node->right, sentinel, out);
}

template <typename T>
std::vector<T> inorderVector(const RBTree<T>& tree) {
    std::vector<T> out;
    collectInorder(tree.getRoot(), tree.getNIL(), out);
    return out;
}

// ---------------------------------------------------------------------
// Type-Specific Core Tests
// ---------------------------------------------------------------------

void test_int_domain_cases() {
    std::cout << "test_int_domain_cases (negatives, duplicate rejection, boundaries) ... ";
    RBTree<int> t;

    // Test mixing negative numbers, zero, and boundary limits
    std::vector<int> inputs = {0, -50, 100, -100, 50, -25, 25, -2147483647, 2147483647};
    for (int v : inputs) t.insert(v);

    assert(isValidRBTree(t));

    // Test duplicate insertions (should gracefully reject duplicates)
    t.insert(0);
    t.insert(-50);
    t.insert(100);
    assert(isValidRBTree(t));
    assert(inorderVector(t).size() == inputs.size()); // Count remains original

    // Min and Max checks
    assert(t.getMin(t.getRoot())->val == -2147483647);
    assert(t.getMax(t.getRoot())->val == 2147483647);

    // Delete zero (root/internal balance checks across zero boundary)
    t.remove(0);
    assert(!t.contains(0));
    assert(isValidRBTree(t));

    std::cout << "OK\n";
}

void test_char_domain_cases() {
    std::cout << "test_char_domain_cases (ASCII case sensitivity & punctuation) ... ";
    RBTree<char> t;

    // Mixed case characters, symbols, numbers in char form
    std::string char_stream = "aZ1!bY2@cX3#";
    for (char c : char_stream) t.insert(c);

    assert(isValidRBTree(t));

    auto sorted = inorderVector(t);
    // Verify standard C++ char ordering property (ASCII order)
    for (size_t i = 1; i < sorted.size(); ++i) {
        assert(sorted[i - 1] < sorted[i]);
    }

    // Lookup assertions
    assert(t.contains('a'));
    assert(t.contains('Z'));
    assert(t.contains('#'));
    assert(!t.contains('z')); // lowercase 'z' wasn't inserted

    // Remove punctuation symbols
    t.remove('!');
    t.remove('@');
    t.remove('#');
    assert(isValidRBTree(t));
    assert(!t.contains('#'));

    std::cout << "OK\n";
}

void test_string_domain_cases() {
    std::cout << "test_string_domain_cases (prefix collisions & variable length) ... ";
    RBTree<std::string> t;

    // Tricky string cases: Prefixes of other strings, varying lengths
    std::vector<std::string> words = {
        "a", "app", "apple", "applet", "application",
        "b", "ba", "ban", "banana", "band", "bandage"
    };

    for (const auto& w : words) t.insert(w);

    assert(isValidRBTree(t));

    // Verify exact lexicographical ordering
    auto sorted = inorderVector(t);
    assert(sorted == words);

    // Partial prefix deletions
    t.remove("app");         // Prefix removal
    t.remove("application"); // Tail removal
    assert(isValidRBTree(t));

    assert(!t.contains("app"));
    assert(!t.contains("application"));
    assert(t.contains("apple")); // Leaves surrounding siblings intact
    assert(t.contains("applet"));

    std::cout << "OK\n";
}

void test_structural_rotations() {
    std::cout << "test_structural_rotations (sequential cascading rebalance) ... ";
    RBTree<int> t;

    // Monotonic insertions force continuous left/right rotations & re-colorings
    for (int i = 1; i <= 50; ++i) {
        t.insert(i);
        assert(isValidRBTree(t));
    }

    // Monotonic removals back to empty
    for (int i = 1; i <= 50; ++i) {
        t.remove(i);
        assert(isValidRBTree(t));
    }

    assert(t.getRoot() == t.getNIL());
    std::cout << "OK\n";
}

void test_stress_randomized() {
    std::cout << "test_stress_randomized ... ";
    RBTree<int> t;

    // Deterministic pseudo-random pattern
    for (int i = 0; i < 300; ++i) {
        int val = (i * 97 + 13) % 150;
        t.insert(val);
        assert(isValidRBTree(t));
    }

    for (int i = 0; i < 150; ++i) {
        int val = (i * 31 + 7) % 150;
        t.remove(val);
        assert(isValidRBTree(t));
    }

    std::cout << "OK\n";
}

void run_all_tests() {
    std::cout << "===================================================\n";
    std::cout << "       Running RBTree Correctness Test Suite       \n";
    std::cout << "===================================================\n";
    test_int_domain_cases();
    test_char_domain_cases();
    test_string_domain_cases();
    test_structural_rotations();
    test_stress_randomized();
    std::cout << "===================================================\n";
    std::cout << "               ALL TESTS PASSED!                   \n";
    std::cout << "===================================================\n\n";
}

// ---------------------------------------------------------------------
// Main Program Driver
// ---------------------------------------------------------------------

int main() {
    run_all_tests();

    // 1. Integer Tree Visualization
    RBTree<int> int_tree;
    for (int v : {20, 10, 30, 5, 15, 25, 35, 3, 7, 12, 18, 28, 40}) {
        int_tree.insert(v);
    }
    std::cout << "Launching SFML Visualizer for [int] tree (Close window to proceed)...\n";
    Visualizer<RBTree<int>> int_vis(int_tree);
    int_vis();

    // 2. Character Tree Visualization
    RBTree<char> char_tree;
    for (char c : {'M', 'F', 'T', 'C', 'H', 'P', 'W', 'A', 'D', 'K', 'R'}) {
        char_tree.insert(c);
    }
    std::cout << "Launching SFML Visualizer for [char] tree (Close window to proceed)...\n";
    Visualizer<RBTree<char>> char_vis(char_tree);
    char_vis();

    // 3. String Tree Visualization
    RBTree<std::string> string_tree;
    for (const auto& str : {"Red", "Black", "Tree", "Binary", "Search", "Node", "Balance", "Color"}) {
        string_tree.insert(str);
    }
    std::cout << "Launching SFML Visualizer for [std::string] tree...\n";
    Visualizer<RBTree<std::string>> string_vis(string_tree);
    string_vis();

    return 0;
}